USE [GradeHorario]

CREATE TABLE PRE_REQUISITO (
CODIGO_DISCIPLINA VARCHAR(7),
CODIGO_DISCIPLINA_REQUISITO VARCHAR(7),
PRIMARY KEY(CODIGO_DISCIPLINA,CODIGO_DISCIPLINA_REQUISITO)
)

CREATE TABLE DEPARTAMENTO (
CODIGO_DEPARTAMENTO INTEGER PRIMARY KEY,
NOME_DEPARTAMENTO VARCHAR(100)
)

CREATE TABLE CURSO (
CODIGO_CURSO INTEGER PRIMARY KEY,
NOME_CURSO VARCHAR(100),
QTD_FASE INTEGER
)

CREATE TABLE ESPACO (
CODIGO_ESPACO VARCHAR(15) PRIMARY KEY,
TIPO_ESPACO VARCHAR(20),
NUMERO_PC_ESPACO INTEGER,
PROJETOR_ESPACO BIT,
INTERNET_ESPACO BIT,
CAPACIDADE_ESPACO INTEGER,
QUADRO_VIDRO_ESPACO BIT,
QUADRO_BRANCO_ESPACO BIT
)

CREATE TABLE DISCIPLINA_CURSO (
CODIGO_DISCIPLINA VARCHAR(7),
CODIGO_CURSO INTEGER,
CODIGO_TURMA VARCHAR(6),
FASE_DISCIPLINA_CURSO INTEGER,
PRIMARY KEY(CODIGO_DISCIPLINA,CODIGO_CURSO,CODIGO_TURMA),
FOREIGN KEY(CODIGO_CURSO) REFERENCES CURSO (CODIGO_CURSO)
)

CREATE TABLE TURMA (
CODIGO_TURMA VARCHAR(6) PRIMARY KEY
)

CREATE TABLE SEMESTRE (
SEQ_SEMESTRE INTEGER IDENTITY(1,1) PRIMARY KEY,
NOME_SEMESTRE VARCHAR(10)
)

CREATE TABLE PROFESSOR (
CODIGO_PROFESSOR INTEGER PRIMARY KEY,
NOME_PROFESSOR VARCHAR(200),
CODIGO_DEPARTAMENTO INTEGER,
FOREIGN KEY(CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTO (CODIGO_DEPARTAMENTO)
)

CREATE TABLE GRADE_TURMA (
DIA_SEMANA_GRADE INTEGER,
HORARIO_GRADE INTEGER,
SEQ_DISCIPLINA_TURMA INTEGER,
CODIGO_ESPACO VARCHAR(15),
PRIMARY KEY(DIA_SEMANA_GRADE,HORARIO_GRADE, SEQ_DISCIPLINA_TURMA)
)

CREATE TABLE GRADE (
DIA_SEMANA_GRADE INTEGER,
HORARIO_GRADE INTEGER,
PRIMARY KEY(DIA_SEMANA_GRADE,HORARIO_GRADE)
)

CREATE TABLE DISCIPLINA_TURMA (
SEQ_DISCIPLINA_TURMA INTEGER IDENTITY(1,1) PRIMARY KEY,
SEQ_SEMESTRE INTEGER,
CODIGO_CURSO INTEGER,
CODIGO_DISCIPLINA VARCHAR(7),
CODIGO_TURMA VARCHAR(6),
CODIGO_PROFESSOR1 INTEGER,
CODIGO_PROFESSOR2 INTEGER,
CODIGO_PROFESSOR3 INTEGER,
FOREIGN KEY(SEQ_SEMESTRE) REFERENCES SEMESTRE (SEQ_SEMESTRE),
FOREIGN KEY(CODIGO_DISCIPLINA,CODIGO_CURSO,CODIGO_TURMA) REFERENCES DISCIPLINA_CURSO (CODIGO_DISCIPLINA,CODIGO_CURSO,CODIGO_TURMA),
FOREIGN KEY(CODIGO_PROFESSOR1) REFERENCES PROFESSOR (CODIGO_PROFESSOR),
FOREIGN KEY(CODIGO_PROFESSOR2) REFERENCES PROFESSOR (CODIGO_PROFESSOR),
FOREIGN KEY(CODIGO_PROFESSOR3) REFERENCES PROFESSOR (CODIGO_PROFESSOR)
)

CREATE TABLE DISCIPLINA (
CODIGO_DISCIPLINA VARCHAR(7) PRIMARY KEY,
CREDITO_DISCIPLINA INTEGER,
NOME_DISCIPLINA VARCHAR(150),
CODIGO_DEPARTAMENTO INTEGER,
FOREIGN KEY(CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTO (CODIGO_DEPARTAMENTO)
)

ALTER TABLE PRE_REQUISITO ADD FOREIGN KEY(CODIGO_DISCIPLINA) REFERENCES DISCIPLINA (CODIGO_DISCIPLINA)
ALTER TABLE PRE_REQUISITO ADD FOREIGN KEY(CODIGO_DISCIPLINA_REQUISITO) REFERENCES DISCIPLINA (CODIGO_DISCIPLINA)
ALTER TABLE DISCIPLINA_CURSO ADD FOREIGN KEY(CODIGO_DISCIPLINA) REFERENCES DISCIPLINA (CODIGO_DISCIPLINA)
ALTER TABLE DISCIPLINA_CURSO ADD FOREIGN KEY(CODIGO_TURMA) REFERENCES TURMA (CODIGO_TURMA)
ALTER TABLE GRADE_TURMA ADD FOREIGN KEY(CODIGO_ESPACO) REFERENCES ESPACO (CODIGO_ESPACO)
ALTER TABLE GRADE_TURMA ADD FOREIGN KEY(DIA_SEMANA_GRADE,HORARIO_GRADE) REFERENCES GRADE (DIA_SEMANA_GRADE,HORARIO_GRADE)
ALTER TABLE GRADE_TURMA ADD FOREIGN KEY(SEQ_DISCIPLINA_TURMA) REFERENCES DISCIPLINA_TURMA (SEQ_DISCIPLINA_TURMA)