CREATE TABLE PRE_REQUISITO (
CODIGO_DISCIPLINA VARCHAR(10),
CODIGO_DISCIPLINA_REQUISITO VARCHAR(10),
PRIMARY KEY(CODIGO_DISCIPLINA,CODIGO_DISCIPLINA_REQUISITO)
)

CREATE TABLE DISCIPLINA (
CODIGO_DISCIPLINA VARCHAR(10) PRIMARY KEY,
CREDITO_DISCIPLINA INTEGER,
NOME_DISCIPLINA VARCHAR(150),
CODIGO_DEPARTAMENTO INTEGER
)

CREATE TABLE DEPARTAMENTO (
CODIGO_DEPARTAMENTO INTEGER PRIMARY KEY,
NOME_DEPARTAMENTO VARCHAR(100)
)

CREATE TABLE DISCIPLINA_TURMA (
SEQ_TURMA INTEGER,
SEQ_DISCIPLINA_CURSO INTEGER,
PRIMARY KEY(SEQ_TURMA,SEQ_DISCIPLINA_CURSO)
)

CREATE TABLE TURMA (
SEQ_TURMA INTEGER PRIMARY KEY,
NOME_TURMA VARCHAR(10),
CODIGO_SEMESTRE INTEGER
)

CREATE TABLE ESPACO (
CODIGO_ESPACO VARCHAR(15) PRIMARY KEY,
QUADRO_VIDRO_ESPACO BIT,
PROJETOR_ESPACO BIT,
INTERNET_ESPACO BIT,
CAPACIDADE_ESPACO BIT,
QUADRO_BRANCO_ESPACO BIT,
TIPO_ESPACO INTEGER,
NUMERO_PC_ESPACO INTEGER
)

CREATE TABLE ESPACO_TURMA (
CODIGO_ESPACO VARCHAR(15),
SEQ_TURMA INTEGER,
SEQ_DISCIPLINA_CURSO INTEGER,
PRIMARY KEY(CODIGO_ESPACO,SEQ_TURMA,SEQ_DISCIPLINA_CURSO),
FOREIGN KEY(SEQ_TURMA, SEQ_DISCIPLINA_CURSO) REFERENCES DISCIPLINA_TURMA (SEQ_TURMA, SEQ_DISCIPLINA_CURSO)
)

CREATE TABLE CURSO (
CODIGO_CURSO INTEGER PRIMARY KEY,
NOME_CURSO VARCHAR(100)
)

CREATE TABLE PROFESSOR (
NOME_PROFESSOR VARCHAR(200),
CODIGO_PROFESSOR INTEGER PRIMARY KEY,
CODIGO_DEPARTAMENTO INTEGER,
FOREIGN KEY(CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTO (CODIGO_DEPARTAMENTO)
)

CREATE TABLE PROFESSOR_TURMA (
CODIGO_PROFESSOR INTEGER,
SEQ_TURMA INTEGER,
SEQ_DISCIPLINA_CURSO INTEGER,
PRIMARY KEY(CODIGO_PROFESSOR, SEQ_TURMA, SEQ_DISCIPLINA_CURSO),
FOREIGN KEY(SEQ_TURMA, SEQ_DISCIPLINA_CURSO) REFERENCES DISCIPLINA_TURMA (SEQ_TURMA,SEQ_DISCIPLINA_CURSO)
)

CREATE TABLE SEMESTRE (
CODIGO_SEMESTRE INTEGER PRIMARY KEY,
NOME_SEMESTRE VARCHAR(10)
)

CREATE TABLE DISCIPLINA_CURSO (
SEQ_DISCIPLINA_CURSO INTEGER PRIMARY KEY,
FASE_DISCIPLINA_CURSO INTEGER,
CODIGO_CURSO INTEGER,
CODIGO_DISCIPLINA VARCHAR(10),
FOREIGN KEY(CODIGO_CURSO) REFERENCES CURSO (CODIGO_CURSO),
FOREIGN KEY(CODIGO_DISCIPLINA) REFERENCES DISCIPLINA (CODIGO_DISCIPLINA)
)

CREATE TABLE GRADE (
SEQ_GRADE INTEGER PRIMARY KEY,
DIA_SEMANA_GRADE INTEGER,
HORARIO_GRADE INTEGER
)

CREATE TABLE GRADE_TURMA (
SEQ_TURMA INTEGER,
SEQ_DISCIPLINA_CURSO INTEGER,
SEQ_GRADE INTEGER,
PRIMARY KEY(SEQ_TURMA,SEQ_DISCIPLINA_CURSO,SEQ_GRADE),
FOREIGN KEY(SEQ_TURMA, SEQ_DISCIPLINA_CURSO) REFERENCES DISCIPLINA_TURMA (SEQ_TURMA, SEQ_DISCIPLINA_CURSO),
FOREIGN KEY(SEQ_GRADE) REFERENCES GRADE (SEQ_GRADE)
)

ALTER TABLE PRE_REQUISITO ADD FOREIGN KEY(CODIGO_DISCIPLINA) REFERENCES DISCIPLINA (CODIGO_DISCIPLINA)
ALTER TABLE PRE_REQUISITO ADD FOREIGN KEY(CODIGO_DISCIPLINA_REQUISITO) REFERENCES DISCIPLINA (CODIGO_DISCIPLINA)
ALTER TABLE DISCIPLINA ADD FOREIGN KEY(CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTO (CODIGO_DEPARTAMENTO)
ALTER TABLE DISCIPLINA_TURMA ADD FOREIGN KEY(SEQ_TURMA) REFERENCES TURMA (SEQ_TURMA)
ALTER TABLE DISCIPLINA_TURMA ADD FOREIGN KEY(SEQ_DISCIPLINA_CURSO) REFERENCES DISCIPLINA_CURSO (SEQ_DISCIPLINA_CURSO)
ALTER TABLE TURMA ADD FOREIGN KEY(CODIGO_SEMESTRE) REFERENCES SEMESTRE (CODIGO_SEMESTRE)
ALTER TABLE ESPACO_TURMA ADD FOREIGN KEY(CODIGO_ESPACO) REFERENCES ESPACO (CODIGO_ESPACO)
ALTER TABLE PROFESSOR_TURMA ADD FOREIGN KEY(CODIGO_PROFESSOR) REFERENCES PROFESSOR (CODIGO_PROFESSOR)