//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta
//     As alterações neste arquivo serão perdidas se o código for recriado
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class InfraestruturaRegraNegocio
{
    InfraestruturaAcessoDados infraEstrutura;


    //Seleciona todos os espacos
    public List<Modelos.ESPACO> SelecionaTodaInfraEstutura()
    {
        try
        {
            infraEstrutura = new InfraestruturaAcessoDados();

            return infraEstrutura.SelecionaTodaInfraEstutura();
        }
        catch (Exception ex)
        {
            throw new Exception("Erro no método SelecionaTodaEstrutura.\n\nDetalhe: \n\n" + ex.Message);
        }

    }

    public void InsereInfraEstrutura(Modelos.ESPACO)
    {
        
    }
}

