//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta
//     As alterações neste arquivo serão perdidas se o código for recriado
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;

namespace RegraNegocio
{
    public class SelecionaDisciplinaRegraNegocio
    {
        private AcessoDados.SelecionaDisciplinaAcessoDados selecionaDisciplinaAD;

        public DataTable SelecionaTodaDisciplina()
        {
            selecionaDisciplinaAD = new AcessoDados.SelecionaDisciplinaAcessoDados();

            return selecionaDisciplinaAD.SelecionaTodaDisciplina();
        }
    }
}


