//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCIPLINA_TURMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISCIPLINA_TURMA()
        {
            this.GRADE_TURMA = new HashSet<GRADE_TURMA>();
        }
    
        public int SEQ_DISCIPLINA_TURMA { get; set; }
        public Nullable<int> SEQ_SEMESTRE { get; set; }
        public Nullable<int> CODIGO_CURSO { get; set; }
        public string CODIGO_DISCIPLINA { get; set; }
        public string CODIGO_TURMA { get; set; }
        public Nullable<int> CODIGO_PROFESSOR1 { get; set; }
        public Nullable<int> CODIGO_PROFESSOR2 { get; set; }
        public Nullable<int> CODIGO_PROFESSOR3 { get; set; }
    
        public virtual DISCIPLINA_CURSO DISCIPLINA_CURSO { get; set; }
        public virtual PROFESSOR PROFESSOR { get; set; }
        public virtual PROFESSOR PROFESSOR1 { get; set; }
        public virtual PROFESSOR PROFESSOR2 { get; set; }
        public virtual SEMESTRE SEMESTRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRADE_TURMA> GRADE_TURMA { get; set; }
    }
}
