//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE_TURMA
    {
        public int DIA_SEMANA_GRADE { get; set; }
        public int HORARIO_GRADE { get; set; }
        public int SEQ_SEMESTRE { get; set; }
        public int CODIGO_CURSO { get; set; }
        public string CODIGO_DISCIPLINA { get; set; }
        public string CODIGO_TURMA { get; set; }
        public string CODIGO_ESPACO { get; set; }
    
        public virtual DISCIPLINA_TURMA DISCIPLINA_TURMA { get; set; }
        public virtual ESPACO ESPACO { get; set; }
        public virtual GRADE GRADE { get; set; }
    }
}
