//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFESSOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROFESSOR()
        {
            this.DISCIPLINA_TURMA = new HashSet<DISCIPLINA_TURMA>();
            this.DISCIPLINA_TURMA1 = new HashSet<DISCIPLINA_TURMA>();
            this.DISCIPLINA_TURMA2 = new HashSet<DISCIPLINA_TURMA>();
        }
    
        public string NOME_PROFESSOR { get; set; }
        public int CODIGO_PROFESSOR { get; set; }
        public Nullable<int> CODIGO_DEPARTAMENTO { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISCIPLINA_TURMA> DISCIPLINA_TURMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISCIPLINA_TURMA> DISCIPLINA_TURMA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISCIPLINA_TURMA> DISCIPLINA_TURMA2 { get; set; }
    }
}
