-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.


CREATE TABLE PRE_REQUISITO (
CODIGO_DISCIPLINA VARCHAR(6),
CODIGO_DISCIPLINA_REQUISITO VARCHAR(6),
PRIMARY KEY(CODIGO_DISCIPLINA, CODIGO_DISCIPLINA_REQUISITO)
)

CREATE TABLE DISCIPLINA (
CODIGO_DISCIPLINA VARCHAR(6) PRIMARY KEY,
CREDITO_DISCIPLINA INTEGER,
NOME_DISCIPLINA VARCHAR(150),
CODIGO_DEPARTAMENTO INTEGER
)

CREATE TABLE SEMESTRE (
CODIGO_SEMESTRE INTEGER PRIMARY KEY,
NOME_SEMESTRE NVARCHAR(10)
)

CREATE TABLE ESPACO (
CODIGO_ESPACO VARCHAR(15) PRIMARY KEY,
QUADRO_VIDRO_ESPACO BIT,
PROJETOR_ESPACO BIT,
INTERNET_ESPACO BIT,
CAPACIDADE_ESPACO INTEGER,
QUADRO_BRANCO_ESPACO BIT,
TIPO_ESPACO BIT,
NUMERO_PC_ESPACO INTEGER
)

CREATE TABLE DEPARTAMENTO (
CODIGO_DEPARTAMENTO INTEGER PRIMARY KEY,
NOME_DEPARTAMENTO NVARCHAR(100)
)

CREATE TABLE PROFESSOR (
NOME_PROFESSOR VARCHAR(200),
CODIGO_PROFESSOR INTEGER PRIMARY KEY,
CODIGO_DEPARTAMENTO INTEGER,
FOREIGN KEY(CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTO (CODIGO_DEPARTAMENTO)
)

CREATE TABLE GRADE (
SEQ_GRADE INTEGER PRIMARY KEY,
DIA_SEMANA_GRADE INTEGER,
HORARIO_GRADE INTEGER,
SEQ_TURMA INTEGER,
SEQ_DISCIPLINA_CURSO INTEGER
)

CREATE TABLE CURSO (
CODIGO_CURSO INTEGER PRIMARY KEY,
NOME_CURSO VARCHAR(100)
)

CREATE TABLE DISCIPLINA_CURSO (
SEQ_DISCIPLINA_CURSO INTEGER PRIMARY KEY,
CODIGO_CURSO INTEGER,
CODIGO_DISCIPLINA VARCHAR(6),
FASE_DISCIPLINA_CURSO INTEGER,
FOREIGN KEY(CODIGO_DISCIPLINA) REFERENCES DISCIPLINA (CODIGO_DISCIPLINA)
)

CREATE TABLE TURMA (
SEQ_TURMA INTEGER PRIMARY KEY,
NOME_TURMA VARCHAR(10),
CODIGO_SEMESTRE INTEGER
)

CREATE TABLE DISCIPLINA_TURMA (
SEQ_TURMA INTEGER,
SEQ_DISCIPLINA_CURSO INTEGER,
PRIMARY KEY(SEQ_TURMA,SEQ_DISCIPLINA_CURSO),
FOREIGN KEY(SEQ_TURMA) REFERENCES TURMA (SEQ_TURMA),
FOREIGN KEY(SEQ_DISCIPLINA_CURSO) REFERENCES DISCIPLINA_CURSO (SEQ_DISCIPLINA_CURSO)
)

CREATE TABLE PROFESSOR_TURMA (
CODIGO_PROFESSOR INTEGER,
SEQ_TURMA INTEGER,
SEQ_DISCIPLINA_CURSO INTEGER,
PRIMARY KEY(CODIGO_PROFESSOR,SEQ_TURMA,SEQ_DISCIPLINA_CURSO),
FOREIGN KEY(CODIGO_PROFESSOR) REFERENCES PROFESSOR (CODIGO_PROFESSOR),
FOREIGN KEY(SEQ_TURMA, SEQ_DISCIPLINA_CURSO) REFERENCES DISCIPLINA_TURMA (SEQ_TURMA, SEQ_DISCIPLINA_CURSO)
)

CREATE TABLE ESPACO_TURMA (
CODIGO_ESPACO VARCHAR(15),
SEQ_TURMA INTEGER,
SEQ_DISCIPLINA_CURSO INTEGER,
PRIMARY KEY(CODIGO_ESPACO,SEQ_TURMA,SEQ_DISCIPLINA_CURSO),
FOREIGN KEY(CODIGO_ESPACO) REFERENCES ESPACO (CODIGO_ESPACO),
FOREIGN KEY(SEQ_TURMA, SEQ_DISCIPLINA_CURSO) REFERENCES DISCIPLINA_TURMA (SEQ_TURMA, SEQ_DISCIPLINA_CURSO)
)

ALTER TABLE PRE_REQUISITO ADD FOREIGN KEY(CODIGO_DISCIPLINA) REFERENCES DISCIPLINA (CODIGO_DISCIPLINA)
ALTER TABLE PRE_REQUISITO ADD FOREIGN KEY(CODIGO_DISCIPLINA_REQUISITO) REFERENCES DISCIPLINA (CODIGO_DISCIPLINA)
ALTER TABLE DISCIPLINA ADD FOREIGN KEY(CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTO (CODIGO_DEPARTAMENTO)
ALTER TABLE GRADE ADD FOREIGN KEY(SEQ_TURMA,SEQ_DISCIPLINA_CURSO) REFERENCES DISCIPLINA_TURMA (SEQ_TURMA,SEQ_DISCIPLINA_CURSO)
ALTER TABLE DISCIPLINA_CURSO ADD FOREIGN KEY(CODIGO_CURSO) REFERENCES CURSO (CODIGO_CURSO)
ALTER TABLE TURMA ADD FOREIGN KEY(CODIGO_SEMESTRE) REFERENCES SEMESTRE (CODIGO_SEMESTRE)