SELECT HORARIO_GRADE, DIA_SEMANA_GRADE, CODIGO_DISCIPLINA, NOME_TURMA, CODIGO_ESPACO,
CODIGO_PROFESSOR1, CODIGO_PROFESSOR2, CODIGO_PROFESSOR3
	FROM DISCIPLINA_TURMA AS DISC_TUR
	INNER JOIN 
		(SELECT SEQ_DISCIPLINA_CURSO, CODIGO_DISCIPLINA FROM DISCIPLINA_CURSO
			WHERE FASE_DISCIPLINA_CURSO = 1 AND CODIGO_CURSO = 655) AS DISC 
		ON DISC.SEQ_DISCIPLINA_CURSO = DISC_TUR.SEQ_DISCIPLINA_CURSO
	INNER JOIN
		(SELECT TURMA.SEQ_TURMA, TURMA.NOME_TURMA FROM SEMESTRE
			INNER JOIN TURMA 
				ON TURMA.SEQ_SEMESTRE = SEMESTRE.SEQ_SEMESTRE
			WHERE NOME_SEMESTRE = '2016/1') AS TRM
		ON TRM.SEQ_TURMA = DISC_TUR.SEQ_TURMA
	INNER JOIN 
		ESPACO_TURMA AS ESP_TRM 
			ON ESP_TRM.SEQ_TURMA = DISC_TUR.SEQ_TURMA AND
				ESP_TRM.SEQ_DISCIPLINA_CURSO = DISC_TUR.SEQ_TURMA
	INNER JOIN 
		GRADE_TURMA AS GRD_TRM
			ON GRD_TRM.SEQ_DISCIPLINA_CURSO = DISC_TUR.SEQ_DISCIPLINA_CURSO AND
				GRD_TRM.SEQ_TURMA = DISC_TUR.SEQ_TURMA