-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE GRADE (
SEQ_GRADE INTEGER PRIMARY KEY,
DIA_SEMANA_GRADE INTEGER,
HORARIO_GRADE INTEGER,
SEQ_TURMA INTEGER
)

CREATE TABLE ESPACO (
CODIGO_ESPACO VARCHAR(15) PRIMARY KEY,
PROJETOR_ESPACO BOOLEAN,
INTERNET_ESPACO BOOLEAN,
CAPACIDADE_ESPACO INTEGER,
QUADRO_BRANCO_ESPACO BOOLEAN,
TIPO_ESPACO INTEGER,
QUADRO_VIDRO_ESPACO BOOLEAN,
NUMERO_PC_ESPACO INTEGER
)

CREATE TABLE CURSO (
CODIGO_CURSO INTEGER PRIMARY KEY,
NOME_CURSO VARCHAR(100)
)

CREATE TABLE DISCIPLINA (
NOME_DISCIPLINA VARCHAR(150),
CODIGO_DISCIPLINA VARCHAR(6) PRIMARY KEY,
CREDITO_DISCIPLINA INTEGER,
CODIGO_DEPARTAMENTO INTEGER
)

CREATE TABLE PROFESSOR (
NOME_PROFESSOR VARCHAR(200),
CODIGO_PROFESSOR INTEGER PRIMARY KEY,
CODIGO_DEPARTAMENTO INTEGER
)

CREATE TABLE DEPARTAMENTO (
NOME_DEPARTAMENTO VARCHAR(100),
CODIGO_DEPARTAMENTO INTEGER PRIMARY KEY
)

CREATE TABLE SEMESTRE (
CODIGO_SEMESTRE INTEGER PRIMARY KEY,
NOME_SEMESTRE VARCHAR(10)
)

CREATE TABLE TURMA (
SEQ_TURMA INTEGER PRIMARY KEY,
NOME_TURMA VARCHAR(10),
CODIGO_SEMESTRE INTEGER,
FOREIGN KEY(CODIGO_SEMESTRE) REFERENCES SEMESTRE (CODIGO_SEMESTRE)
)

CREATE TABLE PRE_REQUISITO (
CODIGO_DISCIPLINA VARCHAR(6),
CODIGO_DISCIPLINA_REQUISITO VARCHAR(6)
)

CREATE TABLE DISCIPLINA_CURSO (
CODIGO_CURSO INTEGER,
CODIGO_DISCIPLINA VARCHAR(6),
SEQ_DISCIPLINA_CURSO INTEGER PRIMARY KEY,
FASE_DISCIPLINA_CURSO INTEGER,
FOREIGN KEY(CODIGO_CURSO) REFERENCES CURSO (CODIGO_CURSO),
FOREIGN KEY(CODIGO_DISCIPLINA) REFERENCES DISCIPLINA (CODIGO_DISCIPLINA)
)

CREATE TABLE DISCIPLINA_TURMA (
SEQ_TURMA INTEGER,
SEQ_DISCIPLINA_CURSO INTEGER,
FOREIGN KEY(SEQ_TURMA) REFERENCES TURMA (SEQ_TURMA),
FOREIGN KEY(SEQ_DISCIPLINA_CURSO) REFERENCES DISCIPLINA_CURSO (SEQ_DISCIPLINA_CURSO)
)

CREATE TABLE PROFESSOR_TURMA (
SEQ_TURMA INTEGER,
CODIGO_PROFESSOR INTEGER,
FOREIGN KEY(SEQ_TURMA) REFERENCES TURMA (SEQ_TURMA),
FOREIGN KEY(CODIGO_PROFESSOR) REFERENCES PROFESSOR (CODIGO_PROFESSOR)
)

CREATE TABLE ESPACO_TURMA (
CODIGO_ESPACO VARCHAR(15),
SEQ_TURMA INTEGER,
FOREIGN KEY(CODIGO_ESPACO) REFERENCES ESPACO (CODIGO_ESPACO),
FOREIGN KEY(SEQ_TURMA) REFERENCES TURMA (SEQ_TURMA)
)

ALTER TABLE GRADE ADD FOREIGN KEY(SEQ_TURMA) REFERENCES TURMA (SEQ_TURMA)
ALTER TABLE DISCIPLINA ADD FOREIGN KEY(CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTO (CODIGO_DEPARTAMENTO)
ALTER TABLE PROFESSOR ADD FOREIGN KEY(CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTO (CODIGO_DEPARTAMENTO)
