/*  RESTRIÇÕES
	• curso
	• fase
	• semestre
*/

SELECT GRD_TRM.HORARIO_GRADE, GRD_TRM.DIA_SEMANA_GRADE, 
	GRD_TRM.CODIGO_ESPACO, DISC_TRM.CODIGO_TURMA, 
	DISC_TRM.CODIGO_DISCIPLINA, DISC_TRM.CODIGO_PROFESSOR1,
	DISC_TRM.CODIGO_PROFESSOR2, DISC_TRM.CODIGO_PROFESSOR3
 
FROM 
	DISCIPLINA_TURMA AS DISC_TRM
	INNER JOIN
	(SELECT * FROM DISCIPLINA_CURSO AS DISC_CUR
		WHERE FASE_DISCIPLINA_CURSO = 1 AND
		CODIGO_CURSO = 652) AS DISC_CUR
	ON DISC_TRM.CODIGO_CURSO = DISC_CUR.CODIGO_CURSO AND
	DISC_TRM.CODIGO_DISCIPLINA = DISC_CUR.CODIGO_DISCIPLINA AND
	DISC_TRM.CODIGO_TURMA = DISC_CUR.CODIGO_TURMA
	INNER JOIN
	GRADE_TURMA AS GRD_TRM
	ON GRD_TRM.SEQ_DISCIPLINA_TURMA = DISC_TRM.SEQ_DISCIPLINA_TURMA
	WHERE DISC_TRM.SEQ_SEMESTRE = 9