//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta
//     As alterações neste arquivo serão perdidas se o código for recriado
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Disciplina
{
    //
    // Código da disciplina
    //
    public string codigoDisciplina
    {
        get;
        set;
    }

    //
    // Nome da Disciplina
    // 
    public string nomeDisciplina
    {
        get;
        set;
    }

    public int creditoDisciplina
    {
        get;
        set;
    }

    //
    public static string CODIGO_DISCIPLINA
    {
        get { return "CODIGO_DISCIPLINA"; }
    }

    //
    public static string CREDITO_DISCIPLINA
    {
        get { return "CREDITO_DISCIPLINA"; }
    }

    public static string NOME_DISCIPLINA
    {
        get { return "NOME_DISCIPLINA"; }
    }
}

