//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta
//     As alterações neste arquivo serão perdidas se o código for recriado
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FaseAcessoDados
{
    //
    // Insere uma nova fase com, o valor da última fase mais um, no banco de dados
    //
    public void InsereFase() { }

    //
    // Edita os atributos da fase indicada de acordo com os dados fornecidos
    //
    public void EditaFase() { }

    //
    // Deleta a fase especificada
    //
    public void ApagaFase() { }

    //
    // Retorna todas as fases cadastradas
    //
    public void SelecionaTodaFase() { }

    //
    // Retorna as fase que contém o nome indicado -- REVER O FILTRO
    //
    public void SelecionaFase(string filtro) { }

}

