//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta
//     As alterações neste arquivo serão perdidas se o código for recriado
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GradeHorarioAcessoDados
{
    //
    // Insere uma nova grade no banco de dados
    //
    public void InsereGrade() { }

    //
    // Edita os atributos da grade indicada de acordo com os dados fornecidos
    //
    public void EditaGrade() { }

    //
    // Deleta a grade especificada
    //
    public void ApagaGrade() { }

    //
    // Retorna todas as grade cadastradas
    //
    public void SelecionaTodaGrade() { }

    //
    // Retorna as grade que contém o nome indicado -- REVER O FILTRO
    //
    public void SelecionaGrade(string filtro) { }
}

