//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta
//     As alterações neste arquivo serão perdidas se o código for recriado
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class InfraestruturaAcessoDados
{

    //
    // Insere uma nova disciplina no banco de dados
    //
    public void InsereInfraEstrutura() { }

    //
    // Edita os atributos da disciplina indicada de acordo com os dados fornecidos
    //
    public void EditaInfraEstrutura() { }

    //
    // Deleta a disciplina especificada
    //
    public void ApagaInfraEstutura() { }

    //
    // Retorna todas as disciplinas cadastradas
    //
    public List<Modelos.ESPACO> SelecionaTodaInfraEstutura()
    {
        try
        {
            using (Modelos.Entidade contexto = new Modelos.Entidade())
            {
                return contexto.ESPACO.ToList();
            }
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }
    }

    //
    // Retorna as disciplinas que contém o nome indicado -- REVER O FILTRO
    //
    public void SelecionaInfraEstutura(string filtro) { }
}

