//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta
//     As alterações neste arquivo serão perdidas se o código for recriado
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;

namespace AcessoDados
{
    public class ProfessorAcessoDados
    {
        StringBuilder sql;
        SqlCommand comandoSql;
        DataTable dadosTabela;

        //
        // Insere um professor no banco de dados
        //
        public void InsereProfessor(Modelos.PROFESSOR professor)
        {
            using (Modelos.Entidade contexto = new Modelos.Entidade())
            {
                Modelos.PROFESSOR profExiste = contexto.PROFESSOR.Find(professor.CODIGO_PROFESSOR);

                if (profExiste != null)
                {
                    throw new Exception("Já existe um professor com a identificação informada.");
                }


                Modelos.DEPARTAMENTO depto = contexto.DEPARTAMENTO.Find(professor.CODIGO_DEPARTAMENTO);

                if (depto == null)
                {
                    throw new Exception("O departamento indicado não existe!\nCertifique-se que nenhuma outra aplicação esteja manipulando o banco de dados!");
                }

                professor.DEPARTAMENTO = depto;

                contexto.PROFESSOR.Add(professor);
                contexto.SaveChanges();
            }

        }

        //
        // Edita os atributos do professor indicado de acordo com os dados fornecidos
        //
        public void EditaProfessor() { }

        //
        // Apaga o professor especificado
        //
        public void ApagaProfessor() { }

        //
        // Retorna todos os professores cadastrados e os departamentos aos quais estão vinculados
        //
        public DataTable SelecionaTodoProfessor()
        {
            sql = new StringBuilder();
            comandoSql = new SqlCommand();

            try
            {
                using (SqlConnection conexao = new SqlConnection(Conexao.stringConexao))
                {
                    conexao.Open();

                    sql.Append("SELECT PROFESSOR.*, NOME_DEPARTAMENTO FROM PROFESSOR INNER JOIN DEPARTAMENTO");
                    sql.Append(" ON PROFESSOR.CODIGO_DEPARTAMENTO = DEPARTAMENTO.CODIGO_DEPARTAMENTO");
                    sql.Append(" ORDER BY NOME_PROFESSOR ASC");

                    comandoSql.CommandText = sql.ToString();
                    comandoSql.Connection = conexao;
                    DataTable dadoTabela = new DataTable();

                    dadoTabela.Load(comandoSql.ExecuteReader());

                    /*      MODO ALTERNATIVO

                    using (Modelos.Entidade ctx = new Modelos.Entidade())
                    {
                        var query = (from prof in ctx.PROFESSOR
                                     join dep in ctx.DEPARTAMENTO on prof.CODIGO_DEPARTAMENTO equals dep.CODIGO_DEPARTAMENTO
                                     orderby prof.NOME_PROFESSOR
                                     select new { prof, dep}).ToList();

                        return AcessoDados.UtilidadeAcessoDados.ListToDataTable(query);
                    }*/

                    return dadoTabela;
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        //
        // Retorna o professor que contém o nome indicado -- REVER O FILTRO
        //
        public DataTable SelecionaProfessor(Modelos.PROFESSOR professor)
        {
            try
            {
                using (SqlConnection conexao = new SqlConnection(Conexao.stringConexao))
                {
                    sql = new StringBuilder();
                    comandoSql = new SqlCommand();

                    sql.Append("SELECT PROFESSOR.*, NOME_DEPARTAMENTO");
                    sql.Append(" FROM PROFESSOR INNER JOIN DEPARTAMENTO");
                    sql.Append(" ON PROFESSOR.CODIGO_DEPARTAMENTO = DEPARTAMENTO.CODIGO_DEPARTAMENTO");
                    sql.Append(" WHERE PROFESSOR.NOME_PROFESSOR LIKE '@NOME%';");



                    comandoSql.CommandText = sql.ToString();
                    comandoSql.Parameters.AddWithValue("@NOME", professor.NOME_PROFESSOR);
                    comandoSql.Connection = conexao;
                    dadosTabela.Load(comandoSql.ExecuteReader());

                    return dadosTabela;
                }


            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        //
        // Retorna uma lista com todos os departamentos cadastrados.
        //
        public DataTable SelecionaTodoDepartamento()
        {
            try
            {
                using (Modelos.Entidade contexto = new Modelos.Entidade())
                {
                    List<Modelos.DEPARTAMENTO> dep = contexto.DEPARTAMENTO.ToList();

                    return AcessoDados.UtilidadeAcessoDados.ListToDataTable(dep);
                }
            }
            catch (Exception)
            {
                //
                throw;
            }
        }

    }


}
