//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta
//     As alterações neste arquivo serão perdidas se o código for recriado
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ProfessorAcessoDados
{
    //
    // Insere um professor no banco de dados
    //
    public void InsereProfessor() { }

    //
    // Edita os atributos do professor indicado de acordo com os dados fornecidos
    //
    public void EditaProfessor() { }

    //
    // Apaga o professor especificado
    //
    public void ApagaProfessor() { }

    //
    // Retorna todos os professores cadastrados
    //
    public void SelecionaTodaProfessor() { }

    //
    // Retorna o professor que contém o nome indicado -- REVER O FILTRO
    //
    public void SelecionaProfessor(string filtro) { }
}

