//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta
//     As alterações neste arquivo serão perdidas se o código for recriado
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SelecionaDisciplinaAcessoDados
{
    //
    // Seleciona todas as disciplinas cadastradas.
    //
    public void SelecionaTodaDisciplina() { }
}

