//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta
//     As alterações neste arquivo serão perdidas se o código for recriado
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;

namespace AcessoDados
{

    public class SelecionaDisciplinaAcessoDados
    {
        StringBuilder sql = new StringBuilder();
        SqlCommand comandoSql = new SqlCommand();

        //
        // Seleciona todas as disciplinas cadastradas.
        //
        public DataTable SelecionaTodaDisciplina()
        {
            try
            {
                sql.Clear();

                sql.Append("SELECT CODIGO_DISCIPLINA, NOME_DISCIPLINA ");
                sql.Append("FROM DISCIPLINA ORDER BY NOME_DISCIPLINA ASC");

                using (SqlConnection conexao = new SqlConnection(Conexao.stringConexao))
                {
                    DataTable dadosTabela = new DataTable();

                    conexao.Open();

                    comandoSql.CommandText = sql.ToString();
                    comandoSql.Connection = conexao;

                    dadosTabela.Load(comandoSql.ExecuteReader());

                    return dadosTabela;
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}
